# Generated by Django 5.2.6 on 2025-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.ManyToManyField(blank=True, related_name='Order', to='home.orderitem'),
        ),
    ]
