# Generated by Django 5.2.6 on 2025-09-20 16:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Pnum',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='des',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='num',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', through='home.OrderItem', to='home.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='default_value', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default_value', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='pnum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(default='default_value', max_length=300),
        ),
    ]
