# Generated by Django 5.2.6 on 2025-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitem',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
