# Generated by Django 5.2.6 on 2025-09-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='home.order'),
            preserve_default=False,
        ),
    ]
