# Generated by Django 5.2.6 on 2025-09-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
    ]
